/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef LIB_H
#define LIB_H

#ifdef _WIN32
#define LIB_EXPORT_FUNC __declspec(dllexport)
#else
#define LIB_EXPORT_FUNC
#endif

#include <string>

namespace lib {
    class Greeter {
        public:
        std::string LIB_EXPORT_FUNC greeting();
    };
}

#endif
